name: opentpod-env
channels:
    - defaults
    - anaconda
    - conda-forge
dependencies:
    - pip=19.1.1
    - python=3.7
    - setuptools
    - tensorflow-gpu=1.15.0
    - pip:
          - -r production.txt
