# Contains extra packages needed for development besides packages in environment.yml
name: opentpod-env
channels:
    - defaults
    - conda-forge
dependencies:
    - pip=19.1.1
    - python=3.7
    - setuptools
    - psycopg2==2.8.3
    - autopep8
    - autoflake
    - isort
    - pudb
    - rope
    - nodejs
    - pip:
          - -r local.txt
